### ISSUE TITLE
TinyTag doesn't work in Ren'Py 8.1

### ISSUE THREAD

**Issue by lauwurence** [GanstaKingofSA/RenPy-Universal-Player#3]
Hello! I hope this project is not dead...

With new changes in `renpy.loader.rpy` https://github.com/renpy/renpy/pull/3423, getting audio duration with the TinyTag library from this project became impossible.

```
I'm sorry, but an uncaught exception occurred.
  File "game/01functions.rpy", line 15, in get_filename_duration
    data = tinytag.TinyTag.get_renpy(filename, image=False)
AttributeError: 'RWops' object has no attribute 'peek'
```
Ren'Py 8.1 Prerelease
